version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  backendmongoserver1:
    container_name: backendmongoserver1
    image: backendmongoserver
    ports:
      - 3006:3000

  backendmongoserver2:
    container_name: backendmongoserver2
    image: backendmongoserver
    ports:
      - 3007:3000

  backendsqlserver1:
    container_name: backendsqlserver1
    image: backendsqlserver
    ports:
      - 3008:5000
  
  backendsqlserver2:
    container_name: backendsqlserver2
    image: backendsqlserver
    ports:
      - 3009:5000
  
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017

  mssqlserver:
    container_name: mssqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    ports:
      - 1433:1433
    volumes:
      - ./sql:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Bonjour123


