version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  auth1:
    container_name: auth1
    image: authentification
    ports:
      - 3006:3006

  auth2:
    container_name: auth2
    image: authentification
    ports:
      - 3007:3006

  bookservice1:
    container_name: backendsqlserver1
    image: backendsqlserver
    ports:
      - 3008:5000
  
  bookservice2:
    container_name: backendsqlserver2
    image: backendsqlserver
    ports:
      - 3009:5000

  mssqlserver:
    container_name: mssqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    ports:
      - 1433:1433
    volumes:
      - ./sql:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Bonjour123


